### ISSUE TITLE
Add remaining component classes

### ISSUE THREAD

**Issue by ericcf** [ericcf/icalendar2#1]
Currently, only Event is present. I need to add To-Do, Journal, Free/Busy, Time Zone and Alarm

**Comment by james-ai** [comment]
Hi Eric,

I'm adding the Alarm and Timezone components. 
Was wondering how you envisaged adding these sub-components? Looks pretty straightforward but I'd appreciate any pointers or heads-up in case of any caveats.

Thanks,
James.

**Comment by ericcf** [comment]
Thanks! I imagine they'll look similar to Event, but you may come across aspects that require a change/refinement somewhere. Let me know if you get stuck.

**Comment by james-ai** [comment]
Making decent progress. Right now some of the code is kind of specific to alarms but can be generalised later. On a tight timescale but will submit a patch (with tests) when I think I have something workable.

**Comment by ericcf** [comment]
I no longer have the time to work on this, and will happily transfer the repository to whomever wants it.
