### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by james-ai** [ericcf/icalendar2#6]
Maybe my grep-fu is just weak but I can't seem to find any code for creating VTIMEZOME components yet I can create one...

Have I completely lost my mind or is the code simply hiding from me somewhere?

**Comment by james-ai** [comment]
Any word on this, Eric?

**Comment by ericcf** [comment]
I have not had a chance to add that feature. If you want to submit a pull request, that would be fantastic! Otherwise, it may have to wait a little.

**Comment by james-ai** [comment]
I'm more than happy to add this feature.

Just wondering how it was that I could create timezones already without any code for that apparently being present. Any thoughts?

**Comment by james-ai** [comment]
Got this written up. I was going to wait for you to pull the alarm stuff in first though. Do you wanna do it all at once or in stages?
